### PR TITLE
Fix : Plugin not working with `api_url = "https://api.datadoghq.eu/"`. Fixes #7

### LINKED ISSUE #7: Plugin not working with `api_url = "https://api.datadoghq.eu/"`
**Describe the bug**
```
> select name, id from datadog_eu.datadog_user
Error: rpc error: code = Internal desc = hydrate function listUsers failed with panic runtime error: invalid memory address or nil pointer dereference
> select name, id from datadog.datadog_user

Time: 7.954036ms
+-----------------------+--------------------------------------+
| name                  | id                                   |
+-----------------------+--------------------------------------+
| <null>                | 130f3218-38b8-11ec-9b20-da7ad0900002 |
| <null>                | 252dcb01-30e1-11ec-9255-da7ad0900002 |
| turbot-router-events  | f0717bea-30b4-405a-9c8f-34f0b3d28804 |
| Lalit Bhardwaj        | 45c9984e-30a0-11ec-9224-da7ad0900002 |
| Subhajit Kumar Mondal | 0f550528-30e1-11ec-9255-da7ad0900002 |
+-----------------------+--------------------------------------+
```

**Steampipe version (`steampipe -v`)**
Example: v0.9.0

**Plugin version (`steampipe plugin list`)**
Example: v0.0.1

**To reproduce**
setup connection config
```
connection "datadog_eu" {
  plugin  = "datadog"
  api_key = "reacted"
  app_key = "reacted"
  api_url = "https://api.datadoghq.eu/"
}

```

### PR DESCRIPTION
**Pull request by LalitTurbot**
# Example query results
<details>
  <summary>Results</summary>
  
```
Time: 8.975788ms
+-----------------------+--------------------------------------+
| name                  | id                                   |
+-----------------------+--------------------------------------+
| Subhajit Kumar Mondal | 0f550528-30e1-11ec-9255-da7ad0900002 |
| turbot-router-events  | f0717bea-30b4-405a-9c8f-34f0b3d28804 |
| <null>                | 252dcb01-30e1-11ec-9255-da7ad0900002 |
| <null>                | 130f3218-38b8-11ec-9b20-da7ad0900002 |
| Lalit Bhardwaj        | 45c9984e-30a0-11ec-9224-da7ad0900002 |
+-----------------------+--------------------------------------+
> select name, id from datadog_eu.datadog_user

Time: 1.031153257s
+----------------+--------------------------------------+
| name           | id                                   |
+----------------+--------------------------------------+
| Lalit Bhardwaj | 26506476-4765-11ec-9a52-da7ad0900005 |
+----------------+--------------------------------------+
```
</details>

# Connection config
```
connection "datadog" {
  plugin  = "datadog"
  api_key = "reacted"
  app_key = "reacted"
}

connection "datadog_eu" {
  plugin  = "datadog"
  api_key = "reacted"
  app_key = "reacted"
  api_url = "https://api.datadoghq.eu/"
}
```

### CODE REVIEW

File: datadog/utils.go [hunk 1]
```diff
@@ -70,6 +63,8 @@ func connectV1(ctx context.Context, d *plugin.QueryData) (context.Context, *data
 		}
 
 		strings.Split(parsedAPIURL.Host, "/")
+		// If api url is passed, set and use the api name and protocol on ServerIndex{1}
+		ctx = context.WithValue(ctx, datadogV2.ContextServerIndex, 1)
```
Comment (LalitTurbot) [inline datadog/utils.go:67]:
```suggestion
		ctx = context.WithValue(ctx, datadogV1.ContextServerIndex, 1)
```

**Review by cbruno10 — APPROVED** [review]
